version: '3.8'

services:
  heart2heart-db:
    image: postgres:16
    container_name: heart2heart-db
    restart: always
    environment:
      POSTGRES_DB: heart2heart
      POSTGRES_USER: heart2user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - heart2heart-data:/var/lib/postgresql/data
    networks:
      - heart2heart-network

volumes:
  heart2heart-data:

networks:
  heart2heart-network: